<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-IMBM639" failures="2" tests="4" name="Test" time="14.733" errors="0" timestamp="2025-07-20T19:37:14 PKT">
  <testcase classname="api_test.UserTests2" name="testPostUser" time="3.939"/>
  <testcase classname="api_test.UserTests2" name="testGetUserByName" time="6.204">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api_test.UserTests2.testGetUserByName(UserTests2.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api_test.UserTests2" name="testUpdateUserByName" time="2.22"/>
  <testcase classname="api_test.UserTests2" name="deleteUserByName" time="1.166">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api_test.UserTests2.deleteUserByName(UserTests2.java:94)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- deleteUserByName -->
</testsuite> <!-- Test -->
